name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          version: 16.x
      - name: Install Dependencies & Build
        run: |
          npm ci --force
          npm run build
      - name: Test
        run: npm test